language: node_js

env:
  global:
    - secure: IIEC4WqIlugoTq2N/nrZN9j5v0PU13Mo0XacDOKdr18b3cewDQ1n3eicLjVxU+FZh6U1gb1awdIOJ4bnNCgaeiMs2KjAvI8xxsGFwKn996vT2qmJRlOMyowic4Ru0QmkZ+eiHE1FTSfbG7np0WmRpVX788mgpaGJvj7OrQgzVxM=
    - secure: fvBVJ2lVWwPKSW67u3g34a4UM6o8S85YtFHvgaTjOYiyPV2EdAyOpAdABe8jCQBcTy14pXee2wC94/BijhogIQhe9ZUzHMPEISPABPv+WgLDQ80SCioJpe04eUZb7tEih4A4ouAU/iIshoQKEDkFVFjTWy9yCjPqvgDVlk0NNFQ=

node_js:
   - "0.10"

before_script:
  - npm -q install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - $(npm bin)/grunt test

addons:
  sauce_connect: true
