language: node_js

env:
  global:
    - secure: OYtfZTVo0HxCm4vZbZe3oKviBfSuFtzVoLm/90jsD4dmsKZ1HcrpO4S5wbo035gISa5tijtUzEkEMhUoE84EIg6noW/SuF7dpYony51Soo03ZtvGmQVhYAKyxndeztlRxeIE4EzxfycT4bmBbM99XXPpRcwlywPOspYp2dgnTYI=
    - secure: EFIJa3M5WISWWT+idxmjQzyPjq2Klj3vk//GaNzbCECDI2A4ax2H2rNuaEBR3CVhr/lD7waPGI4v/58wkFkvir8JZiCgMxyJDXeQKZJTMp7zCSWPeT10ECUm/etLFfUwq/WbyllXWR1k6wnbbXownaQNmSnyCrJexkooqRcoRN0=

node_js:
   - "0.10"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - $(npm bin)/grunt test

after_success:
  - "./bin/publish_build"
